import React from 'react';
import './contentAgree.scss';

export default function ContentAgree10() {
  return (
    <>
      <div className="contentAgree" id="contentAgree10">
        <div className="containerH">
            <h2>10. Usage Rules: Access Conditions & Restrictions <a href="#top">↑</a></h2>
            <p>If you obtain your Marvel Unlimited subscription via the Website, you must register and/or login to your Marvel Account in order to access the Marvel Unlimited Service or the Content. If you obtain your Marvel Unlimited subscription through in-App subscription via a third party (e.g., an app store), that subscription is also subject to the third party’s terms, and you must be signed into your account on the applicable third party service (e.g., your Apple or Google account) in order to access the Marvel Unlimited Service. <strong>IF YOU INITIALLY PURCHASED YOUR SUBSCRIPTION TO THE MARVEL UNLIMITED SERVICE THROUGH IN-APP SUBSCRIPTION FROM A THIRD PARTY (E.G., APPLE’S APP STORE OR GOOGLE PLAY), UNLESS YOU LINK YOUR IN-APP SUBSCRIPTION TO A MARVEL ACCOUNT, YOU WILL NOT BE ABLE TO ALSO ACCESS THE MARVEL UNLIMITED SERVICE VIA THE MARVEL.COM WEBSITE. TO LEARN HOW TO LINK YOU IN-APP SUBSCRIPTION TO A MARVEL ACCOUNT, PLEASE SEE OUR FAQS <a href="#top">HERE</a></strong>.</p>
            <p>If you were a user of: (a) Marvel Comics app (operated by Comixology), or (b) the Comixology app or webstore (each also operated by Comixology) and you previously synced your Comixology library with your Amazon account, you may be able to migrate your library of Marvel Comics purchased prior to May 2, 2023, to Marvel Unlimited. Users of the iOS version of the Marvel Comics app (operated by Comixology) will need to create and link your Marvel Comics app (operated by Comixology) to a Marvel account to be able to access their Marvel digital comics library in Marvel Unlimited. Android users will not need to do the linking described above because they already have a Marvel account. Detailed directions for how to create and link your Marvel Comics app (operated by Comixology) to a Marvel account are located <a href="#top">here</a>. No purchase of a Marvel Unlimited subscription will be required to read Marvel digital comics you purchased in the Marvel Comics app or the Comixology app or webstore. You will also be able to redeem redemption codes for digital versions of Marvel print comics purchased in comic shops via Marvel.com/redeem; once redeemed, these digital versions will be available to read in Marvel Unlimited starting on May 2, 2023. No purchase of a Marvel Unlimited subscription will be required to redeem these redemption codes.</p>
            <p>Subject to the terms and conditions of this MU Subscriber Agreement, you may download the Marvel Unlimited App and use it on up to five (5) compatible devices concurrently, subject to any applicable third party restrictions (e.g., Apple’s Licensed Application End User License Agreement or the equivalent(s)). We reserve the right to change the number of concurrent devices at our discretion. <a href="#top">Any such changes will be made in accordance with these terms</a>. Subject to the terms and conditions of this MU Subscriber Agreement, solely for the duration of your subscription, Marvel grants you a limited, personal use, non-exclusive, non-transferable, non-assignable, revocable, and non-sublicensable right to 1) install and make non-commercial, personal use only of the Marvel Unlimited Service, and 2) temporarily download and make non-commercial, personal use of the Content we make available to you via the Marvel Unlimited Service.</p>
            <p>This is a license agreement and not an agreement for sale or assignment of any rights in the Marvel Unlimited Service or any Content. Your subscription does not create any ownership interest in the Marvel Unlimited Service or any Content. The Marvel Unlimited Service and the Content, including the copyrights, trademarks, service marks, patents, trade names, trade dress and other intellectual property rights in the Marvel Unlimited Service and the Content, are owned by Marvel, its affiliates and/or its licensors, and is protected by the applicable laws of the United States, as well as other intellectual property laws and treaties.</p>
            <p>You agree that as a condition of your license, you must not and hereby agree not to:</p>
            <ol>
              <li>copy, distribute, transmit, display, perform, broadcast, reproduce, publish, license, create derivative works of, transfer, sell or in any other way commercially exploit the Marvel Unlimited Service or any Content;</li>
              <li>move, decompile, reverse-engineer, disassemble, or other reduce to human-readable form the Marvel Unlimited Service, any Content or underlying technology incorporated into the Marvel Unlimited Service or any Content;</li>
              <li>circumvent or disable any content protection system or digital rights management technology used in connection with the Marvel Unlimited Service or any Content, or access the Marvel Unlimited Service or any Content by any means other than through the Marvel-provided or authorized interfaces;</li>
              <li>bypass, modify, defeat, tamper with or circumvent any of the functions or protections of the Marvel Unlimited Service or any Content, including unauthorized access to any of the Marvel Unlimited Service, Content, accounts, computer systems or networks connected to Marvel through hacking, password mining or any other means;</li>
              <li>access, monitor or copy, or permit a third party to access, monitor or copy, any element of the Marvel Unlimited Service or any Content using a robot, spider, scraper or other automated means or manual process without our express prior written permission;</li>
              <li>damage, disable, overburden or impair the Marvel Unlimited Service or Content, or Marvel’s servers or networks, or interfere with any other user’s use and enjoyment of the Marvel Unlimited Service or Content;</li>
              <li>modify the Marvel Unlimited Service or Content, including but not limited to by removing identification, copyright or other proprietary notices from the Content;</li>
              <li>access or use the Marvel Unlimited Service or any Content for any commercial or business related purpose, or in any commercial establishment or area open to the public (e.g., lobby, bar, restaurant, diner, stadium, casino, club, café, theater, etc.) or build a business utilizing the Marvel Unlimited Service or any Content, whether or not for profit;</li>
              <li>impersonate any person or entity;</li>
              <li>use the Marvel Unlimited Service or any Content for any unlawful purpose, in any unlawful manner, or in any manner that is inconsistent with this MU Subscriber Agreement;</li>
              <li>share your login credentials with third parties; or</li>
              <li>allow or enable third parties to violate the above restrictions.</li>
            </ol>
            <p>Any violation of the restrictions listed above is a violation of the rights of Marvel and/or the copyright holder, and a breach of this MU Subscriber Agreement.</p>
        </div>
      </div>
    </>
  )
}
