import React from 'react';
import './contentAgree.scss';

export default function ContentAgree14() {
  return (
    <>
      <div className="contentAgree" id="contentAgree14">
        <div className="containerH">
            <h2>14. Suspension, Termination and Discontinuation of the Marvel Unlimited Service <a href="#top">↑</a></h2>
            <p>Marvel reserves the right to take appropriate action, including the cancellation of any Marvel Unlimited subscription if, in its discretion, it deems such action necessary. Without limiting the foregoing, you agree that Marvel may, in its sole discretion and without notice or liability to you, restrict, suspend, or terminate your access to part or all of the Marvel Unlimited Service and to any Content if Marvel believes you are using or have used the Marvel Unlimited Service or Content in violation of the MU Subscriber Agreement, the TWDC Terms of Use or applicable law or regulations, or in any manner other than for its intended purpose and in accordance with all other guidelines and requirements applicable thereto. Without limiting the foregoing, Marvel may also restrict or suspend your access to your Marvel Unlimited account for cause and upon reasonable notice to you, which may be communicated electronically, which cause includes but is not limited to: (a) requests from law enforcement or other government authorities, (b) unexpected technical issues or problems, or (c) if Marvel reasonably believes that your Marvel Unlimited account has been created fraudulently, or has been accessed fraudulently, or anyone uses your Marvel Unlimited account for unlawful purposes or for other than its intended purpose. Marvel also reserves the right, after notice to you, to terminate any Marvel Unlimited account and/or Marvel Account that remains inactive for one year (failure to log in to your Marvel Unlimited account or Marvel Account will constitute inactivity for purposes of this MU Subscriber Agreement). You agree that Marvel will not be liable to you or to any third party for any such restriction, suspension, or termination of your access to the Marvel Unlimited Service, your Marvel Account or any Content.</p>
            <p>UPON TERMINATION OF YOUR MARVEL UNLIMITED ACCOUNT AND/OR YOUR MARVEL ACCOUNT, WHETHER TERMINATED BY MARVEL OR YOU (OTHER THAN A CANCELLATION OF YOUR SUBSCRIPTION, IN WHICH CASE YOUR SUBSCRIPTION WILL CONTINUE TO THE END OF THE BILLING PERIOD), YOU WILL IMMEDIATELY LOSE THE RIGHT TO USE THE MARVEL UNLIMITED SERVICE.</p>
            <p>Please note that Marvel is not responsible for any lack of functionality or access to any part of the Marvel Unlimited Service or any Content, or any loss of content or data that is due to: (1) your equipment, devices, operating system or Internet connection, (2) your failure to download the most recent published version of the App, (3) your failure to meet the compatibility requirements, including as a result of your equipment, device, operating system or Internet connection, or (4) your choice to opt-out of, or otherwise limit, restrict or prevent, our use of any information that is necessary to provide such functionality, including by your deletion of such information.</p>
            <p>If Marvel decides to discontinue the Marvel Unlimited Service, Marvel will give you at least sixty (60) calendar days' prior notice. In the event that Marvel changes or discontinues any part of the Marvel Unlimited Service, you acknowledge that you may no longer be able to access Content to the same extent, or at all, as you may have done prior to the change or discontinuation. In no event will Marvel be liable in any way for the discontinuation of the Marvel Unlimited Service or any part thereof, or for the withdrawal of any Content. Your sole remedy in such event is to cancel your subscription.</p>
        </div>
      </div>
    </>
  )
}
