import React from 'react';
import './contentAgree.scss';

export default function ContentAgree5() {
  return (
    <>
      <div className="contentAgree" id="contentAgree5">
        <div className="containerH">
          <h2>5. Subscription Fees & Billing <a href="#top">↑</a></h2>

          <h3 id="contentAgree5-1">5.1 Subscription Fees and Payment Details</h3>
          <p>We may keep your detailed payment information, such as a credit card number and expiration date, on file. You are responsible for keeping your payment method details up-to-date by changing the details when necessary. If your chosen payment method details change or are due to expire during the life of your subscription, Marvel may contact you and/or obtain from your payment card provider updated details including your card number, expiration date and CVV (or equivalent). This enables us to continue to provide you access to the Marvel Unlimited Service. If a payment is not successfully authorized for any reason, we may suspend or terminate your subscription. You also agree that we may charge your payment method you designate to us if you decide to re-activate your Marvel Unlimited subscription.</p>
          <p>You hereby agree to pay all charges to your account, including any applicable taxes, in accordance with billing terms in effect at the time the fee or charge becomes payable. All charges are based on the applicable U.S. Dollar purchase price plus tax, if applicable, and are subject to foreign exchange rates (if applicable) and other fees that the institution issuing your credit card may impose, including foreign transaction fees.</p>
          <p>Your right to use the Marvel Unlimited Service is conditional upon Marvel's receipt of payment. If payment cannot be authorized or if a charge is refunded for any reason, including chargeback, we reserve the right to, immediately and without notice, suspend or terminate your subscription, including your access to the Marvel Unlimited Service and your account. You are required to pay any amounts still owed to us at the time your subscription is suspended or terminated.</p>
          <p>When accessing the Marvel Unlimited Service through a mobile network, your network or roaming provider’s data and other rates and fees will apply. Marvel is not responsible for any other charges you may incur in using the Marvel Unlimited Service.</p>
          <p>Payments are nonrefundable and there are no refunds or credits for partially used billing periods. Marvel may provide a refund, discount or other consideration to any one or more Marvel Unlimited account holder, at Marvel's sole and absolute discretion and without admission of fault or liability.</p>

          <h3 id="contentAgree5-2">5.2 If You Signed up Directly with Marvel on the Website:</h3>
          <h4>&nbsp; (a) Monthly Billing</h4>
          <p>By starting your Marvel Unlimited Service Monthly subscription and providing a payment method, you authorize Marvel to charge you a monthly subscription fee at the then-current rate, plus tax, if applicable (the “Monthly Fee”). Marvel will not charge you a subscription fee for any period in which you have redeemed a free Promotional Trial of the Marvel Unlimited Service or Marvel Unlimited Gift Membership. In the event that Marvel offers a promotional discount on subscription fees applicable to you, if you have properly redeemed such a promotion and comply with the applicable terms and conditions, Marvel will reduce your subscription fee by the appropriate amount for the relevant period.</p>
          <p>The Monthly Fee will be charged at the beginning of your paying subscription and each month thereafter unless and until you cancel. Marvel automatically charges your payment method each month on or around the calendar day corresponding to the commencement of your paying subscription. Marvel reserves the right to change the timing of charging for any reason, including in the event that your payment method is not valid when we attempt to charge it. To view your next renewal date go to <a href="/login">My Account</a> on the Website.</p>

          <h4>&nbsp; (b) Annual Billing</h4>
          <p>By starting your Marvel Unlimited Service Annual or Annual Plus subscription and providing a payment method, you authorize Marvel to charge you an annual subscription fee at the then-current rate, plus tax, if applicable (the “Annual Fee”). Marvel will not charge you a subscription fee for any period in which you have redeemed a free Promotional Trial of the Marvel Unlimited Service or Marvel Unlimited Gift Membership. In the event that Marvel offers a promotional discount on subscription fees applicable to you, if you have properly redeemed such a promotion and comply with the applicable terms and conditions, Marvel will reduce your subscription fee by the appropriate amount for any relevant period.</p>
          <p>The Annual Fee will be charged at the beginning of your paying subscription and each year thereafter unless and until you cancel. Marvel automatically charges your payment method each year on or around the calendar day corresponding to the commencement of your paying subscription. Marvel reserves the right to change the timing of charging for any reason, including, in the event that your payment method is not valid when we attempt to charge it. To view your next renewal date go to <a href="/login">My Account</a> on the Website.</p>

          <h3 id="contentAgree5-3">5.3 If You Signed up Through In-App Subscription with a Third Party:</h3>
          <p>If you obtain your subscription through in-App subscription via a third party (e.g., Apple’s App Store or Google Play), your subscription is subject to the third party’s terms in addition to the MU Subscriber Agreement. For subscriptions obtained via a third party, your billing relationship will be directly with the applicable third party. Any fees charged for your Marvel Unlimited Service will be billed by the applicable third party using the payment information you have provided to such third party. By starting your Marvel Unlimited Service subscription through in-App subscription with a third party and providing a payment method, you agree to pay the subscription fee at the then-current rate (plus tax, if applicable) charged by such third party until cancelled. Such fees are subject to the third party’s pricing policies (including those with respect to exchange rates), which may differ from Marvel’s pricing policies.</p>
          <p>Important information on the applicable terms of sale, payments, taxes, payment methods, your right to cancel a transaction and when you can exercise such right (where applicable), and the technical steps to conclude a transaction, will be detailed in the third party's terms and conditions.</p>
          <p>In order to be billed through the third party you must log in to authenticate your account with that third party for subscription purchases.</p>
          <p>If you wish to change your payment method, you will need to do so through the applicable third party, including by visiting your account with that third party. Payments are nonrefundable and there are no refunds or credits for partially used billing periods. Any price changes to the Marvel Unlimited Service will be handled in accordance with the third party's terms and conditions.</p>
          <p>To cancel your subscription obtained via a third party, please follow the cancellation instructions set forth by the applicable third party.</p>
          <p>The availability of access to the Marvel Unlimited Service via a third party does not represent Marvel's endorsement or responsibility for such party’s services or offerings.</p>

          <h3 id="contentAgree5-4">5.4 Price Changes</h3>
          <p>Marvel reserves the right to change the pricing for the Marvel Unlimited Service or any part of any services Marvel makes available to you in any manner and at any time. In the event of a price change, we will attempt to notify you thirty (30) days in advance of the change by sending an email to the email address you have registered for your account. If you do not wish to accept a price change, you should cancel your subscription in accordance with the instructions included in that email and in this MU Subscriber Agreement. If you do not cancel your subscription after the price change takes effect and prior to the start of your new subscription period, your subscription will be renewed at the price in effect at the time of renewal, without any additional action by you, and you authorize us to charge your payment method for these amounts. We will not be able to notify you of any changes in applicable taxes.</p>
        </div>
      </div>
    </>
  )
}
