import React from 'react';
import './annualPlus.scss'
import AnnualPlusHB from './annualPlusHB';

export default function AnnualPlus() {
    return (
        <>
            <AnnualPlusHB />
            <div className="annual-plus">
                <div className="containerH">
                    <h2>Marvel Unlimited Subscriber Agreement</h2>
                    <h3>Updated and effective as <strong>July 30th, 2020</strong></h3>
                    <p>Marvel Unlimited Annual Plus members may receive, as part of their membership, certain discounts, offers, and experiential opportunities that are not included in Marvel Unlimited Monthly or Annual memberships. As the date set forth above, such benefits include:</p>
                    <ol>
                        <li>Marvel Unlimited Plus Membership Kit: Beginning the first year of the Annual Plus membership and during each subsequent renewal period thereafter, Annual Plus members will be eligible to receive, at the shipping address on file, a membership kit containing Marvel merchandise, comics, and other items selected by Marvel at its sole discretion. Membership kits are subject to availability and Marvel does not guarantee that Annual Plus members will receive the membership kit featured on the <a href="/unlimited">Marvel Unlimited sell page</a> or otherwise advertised at any given time. Please note that Annual Plus Membership Kits may take up to ten (10) weeks to arrive. To update your shipping address, please go to <a href="/login">My Account</a>. Marvel only ships Annual Plus Membership Kits to addresses within the United States (excluding U.S. territories and PO boxes).</li>
                        <li>
                            <a href="https://www.disneystore.com/">ShopDisney.com</a> Discount: Marvel Unlimited Annual Plus members in good standing (as determined by Marvel in its sole discretion) will receive a 10% promo code applicable to select purchases at <a href="https://www.disneystore.com">shopDisney.com</a>, including Marvel products at <a href="https://www.disneystore.com/"> shopDisney.com/Marvel</a>, emailed monthly to the email linked to the Annual Plus membership. Each code is valid for one (1) order only, and becomes invalid once used. Discount offer does not apply to purchases from Disney store and Disney Baby retail or outlet locations in North America or purchases made at Disney Parks and Resorts retail or store locations. Offer excludes sales tax, shipping & handling charges, gift wrap & gift box charges, personalization charges, Disney Theme Park Tickets, Disney Gift Cards, The Walt Disney Company Collectible Shareholder Certificate, subscription products, art & collectibles, books & media (DVDs, Blu-rays, CDs & video games), electronic toys, limited edition, special edition & limited release merchandise, talking action figures, select Star Wars: The Mandalorian merchandise, items related to a charitable promotion, and items from the following brands and collections: Aden & Anais, Afridrille Shoes, Alex and Ani, Barbie Signature Collection, Barefoot Dreams, BaubleBar, Beats by Dre, Bésame, Betsey Johnson, Circle with Disney, Citizen, Cloth Face Masks 4-Pack Set, COACH, ColourPop, Converse, CRISLU, Cubcoats, Disney Designer Jewelry Collection, Disney Fairy Tale Wedding Rings, Disney Parks Designer Collection, Disney Vacation Club, Dooney & Bourke, Enesco, Fantasy Flight Games, Finn & Emma, Freshly Picked, Garmin, Hanna Andersson, Harveys, Jim Shore, kate spade, Le Creuset, LEGO, Lenox, Levi’s, LÍLLÉbaby, Lionel, MagicBand, Marvel Legends Series, Master of Arts, Mickey: The True Original Exhibition, Minnie Mouse: The Main Attraction Collection, Milk Snob, National Geographic, New Balance, Nike, Nixon, Olszewski, Opening Ceremony, Otterbox Electronics, Element Skateboard Decks, Pandora Jewelry, Pandora: The World of Avatar Interactive Banshee Toy, Petunia Pickle Bottom, Pippa & Julie, Precious Moments, rag & bone, Rebecca Hook, RockLove, Royal Selangor, S.T. Dupont, Sentiments, Shinola, Sideshow Collectibles, Star Wars: The Black Series, Starbucks, Steiff, Terez, Thomas Kinkade, TOMS, Tommy Bahama, Vera Bradley, Vinylmation, and Waddle. Additional exclusions may apply. Offer cannot be combined with any other offer or discount, except available shipping offers. No adjustments to prior purchases. Returns and exchanges will be subject to discount taken at time of purchase. Valid packing slip required for returns and exchanges. Offer subject to restrictions and change without notice. Void where prohibited.
                        </li>
                        <li>Invitations to Events: From time to time, Marvel may offer Marvel Unlimited Annual Plus members the opportunity to participate in or attend exclusive, private, or otherwise limited attendance or special events. These offers may vary based on geographic region and be subject to geographical, age, or other limitations. Annual Plus members and their guests (if applicable) may be required to travel or purchase admission in order to attend certain events. Any travel, lodging, or other costs shall be the member’s or their guests’ sole responsibility, unless otherwise stated at the time of offer. Subject to availability.</li>
                    </ol>
                    <p>Marvel reserves the right to offer or retract certain benefits (including those listed above) from time to time. You acknowledge and agree that an offer for a specific benefit does not constitute a guarantee that such benefit will be offered again in the future.</p>
                </div>
            </div>
        </>
    )
}
